development:
  AWS_ACCESS_KEY_ID: "XXXXX"
  AWS_SECRET_ACCESS_KEY: "XXXXX"

test:
  AWS_ACCESS_KEY_ID: "XXXXX"
  AWS_SECRET_ACCESS_KEY: "XXXXX"

production:
  AWS_ACCESS_KEY_ID: "XXXXX"
  AWS_SECRET_ACCESS_KEY: "XXXXX"