# Estonian holiday definitions for the Ruby Holiday gem.
#
# Updated: 2017-06-04.
# Source:  https://en.wikipedia.org/wiki/Public_holidays_in_Estonia
---
months:
  0:
  - name: Suur reede #Good Friday
    regions: [ee]
    function: easter(year)
    function_modifier: -2
    type: informal
  - name: Ülestõusmispühade 1. püha #Easter Sunday
    regions: [ee]
    function: easter(year)
    type: informal
  - name: Nelipühade 1. püha #Whitsunday
    regions: [ee]
    function: easter(year)
    function_modifier: 49
  1:
  - name: Uusaasta #New Year's Day
    regions: [ee]
    mday: 1
    observed: to_weekday_if_weekend(date)
  2:
  - name: Iseseisvuspäev #Independence Day
    mday: 24
    regions: [ee]
  5:
  - name: Kevadpüha #Spring Day
    week: 1
    regions: [ee]
    wday: 1
  6:
  - name: Võidupüha ja jaanilaupäev #Victory Day
    mday: 23
    regions: [ee]
  - name: Jaanipäev #Jaan's Day
    mday: 24
    regions: [ee]
  8:
  - name: Taasiseseisvumispäev #Day of Restoration of Independence
    mday: 20
    regions: [ee]
  12:
  - name: Jõululaupäev #Christmas eve
    regions: [ee]
    mday: 24
  - name: Esimene jõulupüha #Christmas Day
    regions: [ee]
    mday: 25
  - name: Teine jõulupüha #Boxing Day
    regions: [ee]
    mday: 26
tests: |
    {Date.civil(2017,1,1) => 'Uusaasta',
     Date.civil(2017,2,24) => 'Iseseisvuspäev',
     Date.civil(2017,4,14) => 'Suur reede',
     Date.civil(2017,4,16) => 'Ülestõusmispühade 1. püha',
     Date.civil(2017,5,1) => 'Kevadpüha',
     Date.civil(2017,6,4) => 'Nelipühade 1. püha',
     Date.civil(2017,6,23) => 'Võidupüha ja jaanilaupäev',
     Date.civil(2017,6,24) => 'Jaanipäev',
     Date.civil(2017,8,20) => 'Taasiseseisvumispäev',
     Date.civil(2008,12,24) => 'Jõululaupäev',
     Date.civil(2008,12,25) => 'Esimene jõulupüha',
     Date.civil(2008,12,26) => 'Teine jõulupüha'}.each do |date, name|
      assert_equal name, (Holidays.on(date, :ee, :informal)[0] || {})[:name]
    end